public enum ModelState
{
    PLACEMENT_VISIBLE,
    PLACEMENT_INVISIBLE,
    INTERACTABLE,
    TRANSFORM,
    FILTER,
    SOURCECODE,
    ABOUT,
    LEGEND,
    TUTORIAL_TRANSFORM_ONLY,
    TUTORIAL_GAZE_ONLY,
    TUTORIAL_SOURCECODE_ONLY,
    TUTORIAL_FILTER_ONLY
}
